/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Form.java
 *
 * Created on 26/12/2011, 00:22:50
 */
package sp.alvaro.gui;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import sp.alvaro.AppSettings;

/**
 *
 * @author leonardo
 */
public class Form extends javax.swing.JFrame {

    /** Creates new form Form */
    public Form() {
        initComponents();
        
        // usa valores do arquivo "properties" para setar diretórios de trabalho
        // TODO caso não haja nada no properties:
        //      usar diretório de execução da app
        try {
            AppSettings settings = new AppSettings();
            String execDir = System.getProperty("user.dir");
            String dirIn = settings.getCurrentDirectoryIn();
            if (dirIn != null) {
                inTextField.setText(dirIn);
            } 
            else {
                inTextField.setText(execDir);
            }
            String dirOut = settings.getCurrentDirectoryOut();
            if (dirOut != null) {
                outTextField.setText(dirOut);
            } else {
                outTextField.setText(execDir);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            // TODO consertar warning
            JOptionPane.showMessageDialog(this, "Problemas com o arquivo properties",
				          null, JOptionPane.ERROR_MESSAGE);
        }                    
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonProcess = new javax.swing.JButton();
        inTextField = new javax.swing.JTextField();
        outTextField = new javax.swing.JTextField();
        jButtonSelectFileIn = new javax.swing.JButton();
        jButtonSelectFileOut = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jButtonAbout = new javax.swing.JButton();

        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.setDialogTitle("Onde estão as planilha dos professores?");
        jFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Notificador");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText(" - Agregador de notas");

        jLabel3.setText("Entradas:");

        jLabel4.setText("Saídas:");

        jButtonProcess.setText("Processar");
        jButtonProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessActionPerformed(evt);
            }
        });

        inTextField.setEditable(false);
        inTextField.setText("test/resources");
        inTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTextFieldActionPerformed(evt);
            }
        });

        outTextField.setEditable(false);
        outTextField.setText("test/resources/outgui");

        jButtonSelectFileIn.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jButtonSelectFileIn.setText("::");
        jButtonSelectFileIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectFileInActionPerformed(evt);
            }
        });

        jButtonSelectFileOut.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jButtonSelectFileOut.setText("::");
        jButtonSelectFileOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectFileOutActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(181, 36, 45));
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelStatus.setText("Aguardando ordens");

        jButtonAbout.setText("Sobre");
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatus))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSelectFileOut)
                            .addComponent(jButtonSelectFileIn)))
                    .addComponent(jButtonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSelectFileIn)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSelectFileOut)))
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus)
                .addGap(38, 38, 38)
                .addComponent(jButtonProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessActionPerformed

        SwingWorker worker = new SwingWorker<Void, Void>(){

            @Override public Void doInBackground() {
                jLabelStatus.setText("Trabalhando. Espere!");
                ProcessHandler handler = new ProcessHandler(inTextField.getText(), outTextField.getText());
                try {
                    handler.process();
                } catch (IOException ex) {
                    Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                return null;
            }

            @Override public void done() {
                jLabelStatus.setText("Terminado");                        
            }
        };
        worker.execute();
                        
    }//GEN-LAST:event_jButtonProcessActionPerformed

    private void jButtonSelectFileInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectFileInActionPerformed
 
        try {
            jFileChooser.setDialogTitle("Onde estão as planilha dos professores?");            
            AppSettings settings = new AppSettings();
            String dirIn = inTextField.getText();
            if (dirIn != null) {
                jFileChooser.setSelectedFile(new File(dirIn));
            } 
            
            if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
                dirIn = jFileChooser.getSelectedFile().getAbsolutePath();
                inTextField.setText(dirIn);
                settings.setCurrentDirectoryIn(dirIn);
            }        
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Problemas com o arquivo properties",
				          null, JOptionPane.ERROR_MESSAGE);
        }            
    }//GEN-LAST:event_jButtonSelectFileInActionPerformed

    private void jButtonSelectFileOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectFileOutActionPerformed

        try {
            jFileChooser.setDialogTitle("Onde deixar as planilhas das turmas?");            
            AppSettings settings = new AppSettings();
            String dirOut = outTextField.getText();
            if (dirOut != null) {
                jFileChooser.setSelectedFile(new File(dirOut));
            } 
            
            if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
                dirOut = jFileChooser.getSelectedFile().getAbsolutePath();
                outTextField.setText(dirOut);
                settings.setCurrentDirectoryOut(dirOut);
            }        
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Problemas com o arquivo properties",
				          null, JOptionPane.ERROR_MESSAGE);
        }                    
    }//GEN-LAST:event_jButtonSelectFileOutActionPerformed

    private void inTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTextFieldActionPerformed

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
            JOptionPane.showMessageDialog(this, "Autor e copyright:\n"
                    + "Leoanardo Alexandre Ferreira Leite\n"
                    + "Licença: GPLv3",
				          null, JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_jButtonAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inTextField;
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonProcess;
    private javax.swing.JButton jButtonSelectFileIn;
    private javax.swing.JButton jButtonSelectFileOut;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JTextField outTextField;
    // End of variables declaration//GEN-END:variables
}
